services:
  db:
    image: postgres:16
    container_name: lanchas-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: lanchas
      POSTGRES_PASSWORD: lanchas
      POSTGRES_DB: lanchas_dev
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:


